In [25]:
import pandas as pd
import numpy as np

In [26]:
fpath = 'D:/数学建模/数模第四次作业/1数据处理和模型初步建立/total_comment.xlsx'

In [27]:
data = pd.read_excel(fpath, header=0)
data.columns

Index(['ID', '平衡膳食谷类个人摄入状况', '平衡膳食种类个人搭配状况', '平衡膳食种类个人均衡状况', '运动时间情况',
       'BMI健康判断', '全谷物摄入情况', '蔬菜摄入情况', '水果摄入情况', '奶制品摄入情况', '鱼禽蛋肉摄入情况',
       '蛋类摄入情况', '水产品摄入情况', '油摄入情况', '盐情况'],
      dtype='object')

In [28]:
data.iloc[:10]

,ID,平衡膳食谷类个人摄入状况,平衡膳食种类个人搭配状况,平衡膳食种类个人均衡状况,运动时间情况,BMI健康判断,全谷物摄入情况,蔬菜摄入情况,水果摄入情况,奶制品摄入情况,鱼禽蛋肉摄入情况,蛋类摄入情况,水产品摄入情况,油摄入情况,盐情况
0,10001,5,4,4,1,3,3,5,4,1,3,2,1,1,1
1,10002,5,5,5,3,2,3,4,5,4,5,3,4,4,1
2,10003,5,4,3,1,3,1,3,1,1,4,2,2,4,1
3,10004,5,5,5,2,4,2,5,3,3,4,5,4,1,5
4,10005,5,3,3,1,4,1,5,1,1,3,1,3,1,1
5,10006,5,5,5,4,2,1,5,4,1,3,1,4,4,1
6,10007,5,4,5,5,3,2,5,4,4,2,1,3,5,5
7,10008,5,4,4,2,2,3,3,4,1,5,4,3,1,5
8,10009,5,4,4,5,3,2,5,5,2,5,1,5,4,1
9,10010,5,4,3,2,3,4,5,2,2,5,3,5,2,4

In [29]:
data['ID'] = range(1, 1 + data.shape[0])

In [30]:
data.iloc[:10]

,ID,平衡膳食谷类个人摄入状况,平衡膳食种类个人搭配状况,平衡膳食种类个人均衡状况,运动时间情况,BMI健康判断,全谷物摄入情况,蔬菜摄入情况,水果摄入情况,奶制品摄入情况,鱼禽蛋肉摄入情况,蛋类摄入情况,水产品摄入情况,油摄入情况,盐情况
0,1,5,4,4,1,3,3,5,4,1,3,2,1,1,1
1,2,5,5,5,3,2,3,4,5,4,5,3,4,4,1
2,3,5,4,3,1,3,1,3,1,1,4,2,2,4,1
3,4,5,5,5,2,4,2,5,3,3,4,5,4,1,5
4,5,5,3,3,1,4,1,5,1,1,3,1,3,1,1
5,6,5,5,5,4,2,1,5,4,1,3,1,4,4,1
6,7,5,4,5,5,3,2,5,4,4,2,1,3,5,5
7,8,5,4,4,2,2,3,3,4,1,5,4,3,1,5
8,9,5,4,4,5,3,2,5,5,2,5,1,5,4,1
9,10,5,4,3,2,3,4,5,2,2,5,3,5,2,4

In [31]:
def replaceEv(x):
    ev_map = ["不合理", "较不合理", "一般","较合理", "合理"]
    return ev_map[x - 1]



for column in data.columns:
    if column == 'ID':
        continue
    else:
        data[column] = data[column].map(replaceEv)

In [34]:
data.iloc[:10]

,ID,平衡膳食谷类个人摄入状况,平衡膳食种类个人搭配状况,平衡膳食种类个人均衡状况,运动时间情况,BMI健康判断,全谷物摄入情况,蔬菜摄入情况,水果摄入情况,奶制品摄入情况,鱼禽蛋肉摄入情况,蛋类摄入情况,水产品摄入情况,油摄入情况,盐情况
0,1,合理,较合理,较合理,不合理,一般,一般,合理,较合理,不合理,一般,较不合理,不合理,不合理,不合理
1,2,合理,合理,合理,一般,较不合理,一般,较合理,合理,较合理,合理,一般,较合理,较合理,不合理
2,3,合理,较合理,一般,不合理,一般,不合理,一般,不合理,不合理,较合理,较不合理,较不合理,较合理,不合理
3,4,合理,合理,合理,较不合理,较合理,较不合理,合理,一般,一般,较合理,合理,较合理,不合理,合理
4,5,合理,一般,一般,不合理,较合理,不合理,合理,不合理,不合理,一般,不合理,一般,不合理,不合理
5,6,合理,合理,合理,较合理,较不合理,不合理,合理,较合理,不合理,一般,不合理,较合理,较合理,不合理
6,7,合理,较合理,合理,合理,一般,较不合理,合理,较合理,较合理,较不合理,不合理,一般,合理,合理
7,8,合理,较合理,较合理,较不合理,较不合理,一般,一般,较合理,不合理,合理,较合理,一般,不合理,合理
8,9,合理,较合理,较合理,合理,一般,较不合理,合理,合理,较不合理,合理,不合理,合理,较合理,不合理
9,10,合理,较合理,一般,较不合理,一般,较合理,合理,较不合理,较不合理,合理,一般,合理,较不合理,较合理

In [35]:
data.to_excel('D:/数学建模/数模第四次作业/1数据处理和模型初步建立/total_comment_Replace.xlsx')