In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'

In [4]:
df_path = 'D:\\数学建模\\数模第四次作业\\A题-附件\\附件2 慢性病及相关因素流调数据.xlsx'

In [5]:
data = pd.read_excel(df_path, header=1)

In [6]:
data = data.dropna(how='all')

In [7]:
data['出生年'] = 2023 - data['出生年']
data = data.rename(columns={'出生年':'年龄'})

In [9]:
data.insert(data.shape[1], '吸烟', 0)
data

,ID,年龄,性别,民族,Unnamed: 4,文化程度,婚姻状况,职业,是否吸烟,开始吸烟年龄,...,收缩压,舒张压,脉搏,胆固醇,血糖,高密度脂蛋白,低密度脂蛋白,甘油三酯,尿酸,吸烟
0,10001.0,40.0,2.0,1.0,NaN,4.0,1.0,9.0,3.0,NaN,...,98.0,62.0,70.0,3.79,4.61,1.59,1.88,0.91,210.4,0
1,10002.0,29.0,2.0,1.0,NaN,3.0,1.0,13.0,3.0,NaN,...,104.0,70.0,80.0,4.24,4.59,1.59,2.17,0.81,270.6,0
2,10003.0,47.0,1.0,1.0,NaN,4.0,2.0,4.0,1.0,16.0,...,104.0,70.0,80.0,4.84,4.13,1.33,2.92,1.59,298.2,0
3,10004.0,39.0,1.0,1.0,NaN,5.0,2.0,12.0,3.0,NaN,...,126.0,82.0,72.0,5.20,4.68,0.92,3.60,1.84,327.9,0
4,10005.0,55.0,1.0,1.0,NaN,4.0,2.0,9.0,1.0,20.0,...,106.0,70.0,70.0,5.10,4.41,1.37,3.15,1.87,350.9,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7961,NaN,49.0,2.0,1.0,NaN,4.0,2.0,10.0,3.0,NaN,...,90.0,60.0,72.0,4.48,4.61,1.35,2.77,0.56,214.9,0
7962,NaN,78.0,2.0,1.0,NaN,2.0,2.0,10.0,3.0,NaN,...,148.0,60.0,81.0,5.74,5.20,1.24,3.91,0.83,209.8,0
7963,NaN,43.0,1.0,1.0,NaN,3.0,2.0,9.0,1.0,17.0,...,98.0,60.0,72.0,3.92,4.55,0.93,2.46,1.62,227.9,0
7964,NaN,58.0,2.0,1.0,NaN,3.0,2.0,10.0,3.0,NaN,...,108.0,68.0,64.0,4.40,4.54,1.33,2.69,0.64,230.2,0
7965,NaN,55.0,1.0,1.0,NaN,3.0,2.0,4.0,2.0,NaN,...,94.0,70.0,78.0,5.43,4.65,1.12,3.71,1.53,349.7,0

In [10]:
def replace(x):
    if x == 1:
        return "是" 
    elif x == 2: 
        return "已戒烟"
    else:
        return "否"
    
data['吸烟'] = data['是否吸烟'].map(replace)

In [11]:
def replace2(x):
    if x == 1:
        return "是"
    elif x == 2: 
        return "否"
    else:
        return "已戒酒"
data.insert(data.shape[1], '饮酒', 0)
data['饮酒'] = data['是否饮酒'].map(replace2)
data

,ID,年龄,性别,民族,Unnamed: 4,文化程度,婚姻状况,职业,是否吸烟,开始吸烟年龄,...,舒张压,脉搏,胆固醇,血糖,高密度脂蛋白,低密度脂蛋白,甘油三酯,尿酸,吸烟,饮酒
0,10001.0,40.0,2.0,1.0,NaN,4.0,1.0,9.0,3.0,NaN,...,62.0,70.0,3.79,4.61,1.59,1.88,0.91,210.4,否,否
1,10002.0,29.0,2.0,1.0,NaN,3.0,1.0,13.0,3.0,NaN,...,70.0,80.0,4.24,4.59,1.59,2.17,0.81,270.6,否,否
2,10003.0,47.0,1.0,1.0,NaN,4.0,2.0,4.0,1.0,16.0,...,70.0,80.0,4.84,4.13,1.33,2.92,1.59,298.2,是,否
3,10004.0,39.0,1.0,1.0,NaN,5.0,2.0,12.0,3.0,NaN,...,82.0,72.0,5.20,4.68,0.92,3.60,1.84,327.9,否,否
4,10005.0,55.0,1.0,1.0,NaN,4.0,2.0,9.0,1.0,20.0,...,70.0,70.0,5.10,4.41,1.37,3.15,1.87,350.9,是,否
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7961,NaN,49.0,2.0,1.0,NaN,4.0,2.0,10.0,3.0,NaN,...,60.0,72.0,4.48,4.61,1.35,2.77,0.56,214.9,否,否
7962,NaN,78.0,2.0,1.0,NaN,2.0,2.0,10.0,3.0,NaN,...,60.0,81.0,5.74,5.20,1.24,3.91,0.83,209.8,否,否
7963,NaN,43.0,1.0,1.0,NaN,3.0,2.0,9.0,1.0,17.0,...,60.0,72.0,3.92,4.55,0.93,2.46,1.62,227.9,是,否
7964,NaN,58.0,2.0,1.0,NaN,3.0,2.0,10.0,3.0,NaN,...,68.0,64.0,4.40,4.54,1.33,2.69,0.64,230.2,否,否
7965,NaN,55.0,1.0,1.0,NaN,3.0,2.0,4.0,2.0,NaN,...,70.0,78.0,5.43,4.65,1.12,3.71,1.53,349.7,已戒烟,否

In [12]:
data.reset_index()
data['ID'] = range(1, len(data) + 1)

In [13]:
data.columns

Index(['ID', '年龄', '性别', '民族', 'Unnamed: 4', '文化程度', '婚姻状况', '职业', '是否吸烟',
       '开始吸烟年龄',
       ...
       '舒张压', '脉搏', '胆固醇', '血糖', '高密度脂蛋白', '低密度脂蛋白', '甘油三酯', '尿酸', '吸烟', '饮酒'],
      dtype='object', length=236)

In [22]:
data['职业'].fillna(value=0, inplace=True)

0        9.0
1       13.0
2        4.0
3       12.0
4        9.0
        ...
7961    10.0
7962    10.0
7963     9.0
7964    10.0
7965     4.0
Name: 职业, Length: 7836, dtype: float64

In [23]:
def replaceJob(x):
    jobs = ['其他','工人','农民','军人','行政干部','科技人员','医护人员', '教师',
            '金融财务','商业服务人员','家庭妇女','离、退休人员','待业','学生']
    return jobs[int(x)]

data['职业'] = data['职业'].map(replaceJob)

KeyError: '职业'

In [14]:
data.to_csv('D:\\数学建模\\数模第四次作业\\A题-附件\\pre_data.csv')